Algoritmo "Exercício 01"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2023
Var
a: real
b: real


Inicio
Escreval("Digite um número")
leia(a)
Escreval("Digite outro número")
leia(b)

timer(200)

Escreval("Os números digitados foram:",a, " e",b)


Fimalgoritmo