Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/02/2023
Var
// Seção de Declarações das variáveis


Inicio
escreval("Bem-Vindo à Fatec")
escreval("")
escreval("23/02/2023")

escreval("I will make you stay")
Fimalgoritmo