Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/02/2023
Var
// Seção de Declarações das variáveis 
a: inteiro
b: real
c: real

Inicio
a <- 5
b <- 2
c <- 3

escreval(a - b)
escreval("")
escreval(a/b)
escreval("")
escreval(a*c)

escreval("So I won't be the one who said")
Fimalgoritmo