Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/02/2023
Var
contar: inteiro
numero: real



Inicio

para contar de 0 ate 512 passo 52 faca
numero <- contar
escreval(numero)
fimpara

escreval("Out of Time")
Fimalgoritmo