Algoritmo "1.0"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 


Var


a: inteiro

nome: caractere

vet: vetor [1..10] de inteiro

logic: logico




Inicio


a <- 3
nome <- "Ahiem"
logic <- FALSO
se logic = VERDADEIRO entao
escreval(a)
fimse

se logic = FALSO entao
escreva(logic)
escreval("")

fimse


escolha a
caso 2
escreva(a)
escreval("")
outrocaso
escreval(nome)
escreval("")

fimescolha

 escreval("In another life")
Fimalgoritmo