Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/02/2023
Var
// Seção de Declarações das variáveis 
x: inteiro
idade: vetor [0..140] de inteiro

Inicio

para x de 0 ate 140 passo 5 faca
idade[x] <- x
escreval(idade[x])
fimpara

escreval("Yeah, u know my name")

Fimalgoritmo